### ISSUE TITLE
cdo-bindings fail with cdo2.0.0

### ISSUE THREAD

**Issue by larsbuntemeyer** [Try2Code/cdo-bindings#39]
Just realized yesterday when my ci pipeline failed. The [lastet cdo version on conda-forge](https://anaconda.org/conda-forge/cdo
) is `v2.0.0` since yesterday. I had to state explicitly `cdo==1.9.9` to have my ci pipeline run. There is obviously a problem with parsing the cdo version in the bindings.

### what i did

    conda create -n cdo_test python=3 cdo python-cdo

```python
from cdo import Cdo
cdo = Cdo()
```
fails with
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/cdo_test/lib/python3.10/site-packages/cdo.py", line 156, in __init__
    self.operators         = self.__getOperators()
  File "/opt/anaconda3/envs/cdo_test/lib/python3.10/site-packages/cdo.py", line 236, in __getOperators
    version = parse_version(getCdoVersion(self.CDO))
  File "/opt/anaconda3/envs/cdo_test/lib/python3.10/site-packages/cdo.py", line 78, in getCdoVersion
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

works with

    conda create -n cdo_test python=3 cdo==1.9.9 python-cdo

**Comment by larsbuntemeyer** [comment]
seems there has been a switch in the std streams that are parsed by cdo-bindings.

**Comment by Try2Code** [comment]
sry - I notced this pretty soon after the 2.0.0 release and fixed it
